---

- name: Prepare
  hosts: all
  gather_facts: yes

  tasks:
    - name: install required gnupg, for apt gpg keys
      ansible.builtin.apt:
        name: gnupg
        state: present
        
    - name: install apt-transport-http
      ansible.builtin.apt:
        name: apt-transport-http
        state: present
