---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
    - name: check if msedge is installed via checking its version command
      ansible.builtin.shell:
        cmd: /opt/microsoft/msedge/msedge --version
      register: out
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: result
