---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
    - name: check if msedge is installed via checking its version command
      ansible.builtin.command: /opt/microsoft/msedge/msedge --version
      register: out
      changed_when: false
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: result
